name: shopease
description: "ShopEase â€” E-Commerce Showcase App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#6CA8FF"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter_native_splash:
  color: "#6CA8FF"
  image: "assets/splash_logo.png"
  android_12:
    color: "#6CA8FF"
    image: "assets/splash_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
